[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false
maxMessageSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
magicEnabled = false
installTracer = false
fastReruns = true
handle_rerun = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 